<?php
//head link
$this->headLink()->appendStylesheet('/ad-st/vendor/dropify/dropify.min.css');

//inline script
$this->inlineScript()->appendFile('/ad-st/vendor/dropify/dropify.min.js');
$this->inlineScript()->appendFile('/ad-st/js/scripts/product.js');
?>
<div class="page-header">
	<h1 class="page-title">Add product</h1>
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="<?= $this->url('admin-product', ['action' => 'index']); ?>">Manage</a></li>
		<li class="breadcrumb-item active">Add product</li>
	</ol>
	<div class="page-header-actions">
		<button type="button" class="btn btn-sm btn-icon btn-primary btn-round" data-toggle="tooltip" data-original-title="Save">
			<i class="icon md-check" aria-hidden="true"></i>
		</button>
		<button type="button" class="btn btn-sm btn-icon btn-primary btn-round" data-toggle="tooltip" data-original-title="Refresh" onclick="window.location.reload();">
			<i class="icon md-refresh-alt" aria-hidden="true"></i>
		</button>
	</div>
</div>
<div class="page-content">
	<div class="panel">
		<div class="panel-body container-fluid">
			<form action="" method="post" enctype="multipart/form-data">
				<div class="row row-lg">
					<div class="col-md-6 col-lg-4">
						<div class="example-wrap">
							<h4 class="example-title">Tên sản phẩm</h4>
							<input type="text" class="form-control" name="product_name" id="product_name">
						</div>
					</div>
					<div class="col-md-6 col-lg-4">
						<div class="example-wrap">
							<h4 class="example-title">Thể loại</h4>
							<div class="form-group">
								<select class="form-control" name="category" id="category">
									<option>Chọn</option>
									<option>Đồ len</option>
									<option>Chậu cảnh</option>
								</select>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-lg-4">
						<div class="example-wrap">
							<h4 class="example-title">Giá gốc</h4>
							<input type="text" class="form-control" name="original_price" id="original_price">
						</div>
					</div>
					<div class="col-md-6 col-lg-4">
						<div class="example-wrap">
							<h4 class="example-title">Giá bán</h4>
							<input type="text" class="form-control" name="sale_price" id="sale_price">
						</div>
					</div>
					<div class="col-md-6 col-lg-4">
						<div class="example-wrap">
							<h4 class="example-title">% giảm giá</h4>
							<input type="text" class="form-control" name="discount" id="discount">
						</div>
					</div>
					<div class="col-md-6 col-lg-4">
						<div class="example-wrap">
							<h4 class="example-title">Số lượng</h4>
							<input type="text" class="form-control" name="quantity" id="quantity">
						</div>
					</div>
					<div class="col-md-6 col-lg-4">
						<div class="example-wrap">
							<h4 class="example-title">Mô tả ngắn</h4>
							<textarea class="form-control" name="description" id="description" rows="5" placeholder="không quá 200 từ"></textarea>
						</div>
					</div>
					<div class="col-md-6 col-lg-8">
						<div class="example-wrap">
							<h4 class="example-title">Mô tả chi tiết</h4>
							<textarea class="form-control" name="detail" id="detail" rows="5" placeholder="không quá 1000 từ"></textarea>
						</div>
					</div>
					<div class="col-xl-4 col-md-6">
						<div class="example-wrap">
							<h4 class="example-title">Ảnh đại diện</h4>
							<div class="example">
								<input type="file" id="image" name="image"/>
							</div>
						</div>
					</div>
					<div class="col-xl-4 col-md-6 col_btn_more_image">
						<div class="example-wrap">
							<div class="example example-buttons text-center">
								<button type="button" class="btn btn-floating btn-info waves-effect waves-classic" id="btn_more_image"><i class="icon md-plus" aria-hidden="true"></i></button>
							</div>
						</div>
					</div>
				</div>
				<div class="row row-lg">
					<div class="col-md-6 col-lg-4">
						<button type="submit" class="btn btn-lg btn-primary" data-toggle="tooltip" data-original-title="Save"><i class="icon md-check" aria-hidden="true"></i></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>